#!/usr/bin/env bash

# ENV REDIS_PASSWORD, REDIS_HOST, REIDS_PORT:6379,LOG_LEVEL

# params
_CMD_=$(echo $1 | tr /a-z/ /A-Z/)
_KEY_=$2
_VALUE_="$3"

# functions
getkey(){
  clireds redishost hget "$1"
}

setkey(){
  clireds redishost hset "$1"
}

if [ ! -z ${REDIS_ADDR} ]; then
  export REDIS_HOST=$(echo ${REDIS_ADDR} | cut -d '/' -f2)
  export REDIS_PORT=$(echo ${REDIS_ADDR} | cut -d ':' -f2)
fi

# run,execute
if [ "$_CMD_" = "GET" ]; then
  getkey $_KEY_
elif [ "$_CMD_" = "SET" ]; then
  setkey $_KEY_ "$_VALUE_"
fi
