#!/usr/bin/env sh

# params
_CMD_=$(echo $1 | tr /a-z/ /A-Z/)
_KEY_=$2
_VALUE_="$3"

if [ "$_CMD_" = "help" ]; then
  echo "ENV-VAULT:"
  echo -e "\t- VAULT_ADDR"
  echo -e "\t- VAULT_TOKEN"
  echo "ENV-REDIS:"
  echo -e "\t- REDIS_ADDR"
  echo -e "\t- REDIS_PASSWORD"
  exit 0;
fi

if [ -z ${VAULT_ADDR} ]; then
  mybin=/usr/share/cliks/lib/cli_redis
else
  mybin=/usr/share/cliks/lib/cli_vault
fi

# run,execute
${mybin} ${_CMD_} ${_KEY_} ${_VALUE_}
